name: portfolio
description: "Portfolio App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  hooks_riverpod: ^2.6.1
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_generator: ^2.6.2
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraCode-Regular.ttf
          weight: 400
        - asset: assets/fonts/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
